version: "3.4"
services:
  samba:
    image: samba:alpine
    build: ./
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - "./smb.conf:/etc/samba/smb.conf"
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 3
        window: 30s
